[features]
seeds = false
skip-lint = false

[programs.localnet]
the_basement = "GUrBCCME6Cmp9NA4yNSYy1BvKczYPwnqdXSVFAd21sAA"

[programs.devnet]
the_basement = "GUrBCCME6Cmp9NA4yNSYy1BvKczYPwnqdXSVFAd21sAA"

[programs.mainnet]
the_basement = "GUrBCCME6Cmp9NA4yNSYy1BvKczYPwnqdXSVFAd21sAA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "node scripts/initialize.js"
create-test-token = "node scripts/create-test-token.js" 